language: node_js
branches:
  only:
  - master
  - front-end
node_js:
  - '10'
deploy:
  - provider: heroku
    app: community-slices
    github_token: $GITHUB_TOKEN
    api_key: $HEROKU_TOKEN
  - provider: netlify
    site: confident-babbage-08bd18
    auth: $NETLIFY_TOKEN
    local_dir: 'sandbox/dist'
    edge: true # opt in to dpl v2
after_deploy: # This should be run with heroku only
   - if [[ provider == "heroku" ]]; then npm run build:files ; fi
